name: Compile with SourceMod

on: 
  push:
    branches:
     - *
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: [ "1.10", "1.11" ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile basechat
        run: |
          echo -e "\nCompiling basechat.sp..."
          spcomp basechat.sp
        working-directory: '/tmp'